version: '3'
services:
    dev:
        container_name: ${UNAME}
        build:
            context: .
            args: 
                - UID=${UID}
                - GID=${GID}
                - UNAME=${UNAME}
        tty: true
        volumes:
            - ./app:/home/${UNAME}/app
        ports:
            - "3000:3000"